// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aepvjmstgzcuvjskuado.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlcHZqbXN0Z3pjdXZqc2t1YWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDYxNjksImV4cCI6MjA1OTUyMjE2OX0.CteyfiV-GsgoTd2aGa0rEt34AlOdKgC-Bp86dRVqi6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);